"""Run this script once to generate frontend/pages/8_Simulation.py"""
import os, textwrap

out = os.path.join(os.path.dirname(__file__), "frontend", "pages", "8_Simulation.py")

# Build the file content as a raw string with no backslash issues
lines = []

def w(*args):
    lines.extend(args)

w(
'"""Digital Twin AI - Simulation Engine (Milestone 3)"""',
'import os, sys, math',
'import plotly.graph_objects as go',
'import streamlit as st',
'',
'_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))',
'if _ROOT not in sys.path: sys.path.insert(0, _ROOT)',
'',
'from components.theme import inject_theme',
'from components.ui import (',
'    bootstrap_session, empty_state, insight_card, metric_row,',
'    page_header, progress_bar, render_sidebar, require_auth, section_header,',
')',
'',
'st.set_page_config(page_title="Simulation - Digital Twin AI", page_icon="\\U0001f9ec",',
'                   layout="wide", initial_sidebar_state="expanded")',
'inject_theme()',
'bootstrap_session()',
'render_sidebar()',
'require_auth()',
'',
'client = st.session_state.api_client',
'token  = st.session_state.token',
'',
'_PL = dict(',
'    paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",',
'    font=dict(family="Inter", color="#94A3B8", size=12),',
'    margin=dict(l=0, r=0, t=30, b=0),',
'    legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(color="#94A3B8")),',
'    xaxis=dict(gridcolor="rgba(37,99,235,.08)", linecolor="rgba(37,99,235,.15)",',
'               tickfont=dict(color="#64748B")),',
'    yaxis=dict(gridcolor="rgba(37,99,235,.08)", linecolor="rgba(37,99,235,.15)",',
'               tickfont=dict(color="#64748B")),',
')',
'_C = ["#2563EB","#7C3AED","#10B981","#F59E0B","#EF4444","#06B6D4","#EC4899","#14B8A6"]',
'',
'',
'def _api(path, method="get", payload=None):',
'    try:',
'        if method == "get":',
'            return client.get(path, token=token)',
'        return client.post(path, payload=payload, token=token)',
'    except Exception as e:',
'        return {"error": str(e)}',
'',
'',
'def _render_result(result: dict):',
'    if not result or "error" in result:',
'        st.error(result.get("error", "Simulation failed.") if result else "No result.")',
'        return',
'    conf = result.get("confidence_score", 0)',
'    sim_type = result.get("simulation_type","").replace("_"," ").title()',
'    st.markdown(',
'        \'<div style="background:rgba(37,99,235,.08);border:1px solid rgba(37,99,235,.2);\' +',
'        \'border-radius:12px;padding:.75rem 1.25rem;margin-bottom:1rem;\' +',
'        \'display:flex;align-items:center;justify-content:space-between;">\' +',
'        f\'<span style="color:#94A3B8;font-size:.8rem;">Simulation: \' +',
'        f\'<b style="color:#E2E8F0;">{sim_type}</b></span>\' +',
'        f\'<span style="color:#10B981;font-size:.85rem;font-weight:700;">\' +',
'        f\'Confidence: {conf*100:.0f}%</span></div>\',',
'        unsafe_allow_html=True,',
'    )',
'    cur  = result.get("current_state", {})',
'    fut  = result.get("future_state",  {})',
'    diff = result.get("difference",    {})',
'    keys = [k for k in (list(fut.keys()) + list(cur.keys()))',
'            if isinstance(fut.get(k, cur.get(k)), (int, float)) and k not in ("horizon_months","horizon_weeks")]',
'    seen, numeric_keys = set(), []',
'    for k in keys:',
'        if k not in seen: seen.add(k); numeric_keys.append(k)',
'    numeric_keys = numeric_keys[:6]',
'    if numeric_keys:',
'        ncols = min(len(numeric_keys), 3)',
'        cols  = st.columns(ncols)',
'        for i, k in enumerate(numeric_keys[:ncols]):',
'            c_val = float(cur.get(k, 0))',
'            f_val = float(fut.get(k, 0))',
'            d_val = float(diff.get(k, f_val - c_val))',
'            with cols[i]:',
'                label = k.replace("_"," ").title()',
'                f_str = f"{f_val:,.2f}" if abs(f_val) < 1_000_000 else f"{f_val:,.0f}"',
'                up    = d_val >= 0',
'                dstr  = f"+{d_val:,.2f}" if up else f"{d_val:,.2f}"',
'                st.markdown(',
'                    \'<div style="background:rgba(13,17,28,.9);\' +',
'                    \'border:1px solid rgba(37,99,235,.15);border-radius:12px;\' +',
'                    \'padding:1rem;text-align:center;">\' +',
'                    f\'<div style="font-size:.7rem;color:#64748B;text-transform:uppercase;\'+ ',
'                    f\'letter-spacing:.08em;margin-bottom:.4rem;">{label}</div>\' +',
'                    f\'<div style="font-size:1.5rem;font-weight:800;color:#F1F5F9;">{f_str}</div>\' +',
'                    f\'<div style="font-size:.78rem;color:{"#10B981" if up else "#EF4444"};\'+ ',
'                    f\'margin-top:.25rem;">{dstr} vs current</div></div>\',',
'                    unsafe_allow_html=True,',
'                )',
'        if len(numeric_keys) >= 2:',
'            st.markdown("<div style=\'height:.5rem\'></div>", unsafe_allow_html=True)',
'            cur_vals = [float(cur.get(k,0)) for k in numeric_keys]',
'            fut_vals = [float(fut.get(k,0)) for k in numeric_keys]',
'            labels   = [k.replace("_"," ").title() for k in numeric_keys]',
'            fig = go.Figure()',
'            fig.add_trace(go.Bar(name="Current",   x=labels, y=cur_vals, marker_color="#2563EB", opacity=0.85))',
'            fig.add_trace(go.Bar(name="Projected", x=labels, y=fut_vals, marker_color="#10B981", opacity=0.85))',
'            fig.update_layout(**_PL, height=250, barmode="group", title="Current vs Projected")',
'            st.plotly_chart(fig, use_container_width=True)',
'    recs = result.get("recommendations", [])',
'    if recs:',
'        st.markdown("<div style=\'height:.5rem\'></div>", unsafe_allow_html=True)',
'        section_header("\\U0001f4a1", "Recommendations")',
'        for r in recs:',
'            insight_card("tip", r)',
'',
'',
'# ── PAGE HEADER ──────────────────────────────────────────────────────────────',
'page_header("Simulation Engine", "Run what-if scenarios across all life domains")',
'',
'with st.spinner("Loading Digital Twin summary..."):',
'    summary = _api("/api/digital-twin/summary")',
'',
'if summary and "error" not in summary:',
'    overall = summary.get("overall_score", 0)',
'    risk    = summary.get("risk_level", "medium")',
'    metric_row([',
'        dict(icon="\\U0001f9ec", label="Twin Alignment", value=f"{overall:.0f}%",',
'             sub="Overall score", trend_up=overall >= 60,',
'             accent="linear-gradient(90deg,#2563EB,#7C3AED)"),',
'        dict(icon="\\U0001f4da", label="Study",    value=f"{summary.get(\'study_score\',0):.0f}",',
'             sub="/ 100", trend_up=summary.get("study_score",0) >= 60,',
'             accent="linear-gradient(90deg,#7C3AED,#6D28D9)"),',
'        dict(icon="\\U0001f4b0", label="Finance",  value=f"{summary.get(\'financial_score\',0):.0f}",',
'             sub="/ 100", trend_up=summary.get("financial_score",0) >= 60,',
'             accent="linear-gradient(90deg,#06B6D4,#0284C7)"),',
'        dict(icon="\\U0001f525", label="Habits",   value=f"{summary.get(\'habits_score\',0):.0f}",',
'             sub="/ 100", trend_up=summary.get("habits_score",0) >= 60,',
'             accent="linear-gradient(90deg,#F59E0B,#D97706)"),',
'        dict(icon="\\U0001f3c3", label="Fitness",  value=f"{summary.get(\'fitness_score\',0):.0f}",',
'             sub="/ 100", trend_up=summary.get("fitness_score",0) >= 60,',
'             accent="linear-gradient(90deg,#10B981,#059669)"),',
'    ])',
'    st.markdown("<div style=\'height:.5rem\'></div>", unsafe_allow_html=True)',
'    insight_card("warning" if risk == "high" else "tip",',
'                 f"Risk: {risk.upper()} — {summary.get(\'top_insight\',\'\')}",',
'                 "Digital Twin Analysis")',
'else:',
'    st.warning("Could not load Digital Twin summary. Make sure the backend is running.")',
'',
'st.markdown("<div style=\'height:1.5rem\'></div>", unsafe_allow_html=True)',
'',
'# ── TABS ──────────────────────────────────────────────────────────────────────',
'tab_fin, tab_study, tab_hab, tab_fit, tab_cmp, tab_rec, tab_risk = st.tabs([',
'    "  \\U0001f4b0 Financial  ",',
'    "  \\U0001f4da Study  ",',
'    "  \\U0001f525 Habits  ",',
'    "  \\U0001f3c3 Fitness  ",',
'    "  \\U0001f500 Compare  ",',
'    "  \\U0001f4a1 Recommendations  ",',
'    "  \\u26a0\\ufe0f Risk  ",',
'])',
'',
'# ── TAB 1: FINANCIAL ──────────────────────────────────────────────────────────',
'with tab_fin:',
'    section_header("\\U0001f4b0", "Financial Simulation",',
'                   "Model savings, purchases, investments and loans")',
'    fin_sub = st.radio("Type", ["Savings Increase","Major Purchase",',
'                                 "Expense Reduction","Investment Growth","Loan Impact"],',
'                        horizontal=True, key="fin_sub")',
'    st.markdown("<div style=\'height:.5rem\'></div>", unsafe_allow_html=True)',
'    cp1, cp2 = st.columns([1, 1.5], gap="large")',
'    with cp1:',
'        if fin_sub == "Savings Increase":',
'            section_header("\\U0001f4be", "Parameters")',
'            mi = st.slider("Extra Monthly Savings ($)", 50, 5000, 200, 50)',
'            hm = st.slider("Horizon (months)", 1, 60, 12)',
'            if st.button("Run", key="fs1", use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fin_r"] = _api("/api/simulation/financial","post",',
'                        {"sim_type":"savings_increase","monthly_increase":mi,"horizon_months":hm})',
'            fig=go.Figure(go.Scatter(x=list(range(1,hm+1)),',
'                y=[mi*i for i in range(1,hm+1)], mode="lines+markers",',
'                line=dict(color="#10B981",width=2), fill="tozeroy",',
'                fillcolor="rgba(16,185,129,.07)"))',
'            fig.update_layout(**_PL,height=180,title="Projected Extra Savings")',
'            st.plotly_chart(fig,use_container_width=True)',
'        elif fin_sub == "Major Purchase":',
'            section_header("\\U0001f6cd", "Parameters")',
'            pa = st.number_input("Purchase Amount ($)",100.0,1e6,5000.0,100.0)',
'            pm = st.slider("Purchase Month",1,24,3)',
'            hm2= st.slider("Horizon (months)",1,60,12,key="hm2")',
'            if st.button("Run",key="fs2",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fin_r"]=_api("/api/simulation/financial","post",',
'                        {"sim_type":"major_purchase","purchase_amount":pa,',
'                         "purchase_month":pm,"horizon_months":hm2})',
'        elif fin_sub == "Expense Reduction":',
'            section_header("\\u2702\\ufe0f", "Parameters")',
'            rp = st.slider("Reduce Expenses By (%)",1,50,10)',
'            hm3= st.slider("Horizon (months)",1,60,12,key="hm3")',
'            if st.button("Run",key="fs3",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fin_r"]=_api("/api/simulation/financial","post",',
'                        {"sim_type":"expense_reduction","reduction_pct":rp,"horizon_months":hm3})',
'        elif fin_sub == "Investment Growth":',
'            section_header("\\U0001f4c8", "Parameters")',
'            ia = st.number_input("Initial ($)",100.0,1e6,10000.0,500.0)',
'            mc = st.number_input("Monthly Contribution ($)",0.0,50000.0,500.0,50.0)',
'            ar = st.slider("Annual Return (%)",1.0,30.0,8.0,.5)',
'            hm4= st.slider("Horizon (months)",12,120,36,key="hm4")',
'            if st.button("Run",key="fs4",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fin_r"]=_api("/api/simulation/financial","post",',
'                        {"sim_type":"investment_growth","initial_amount":ia,',
'                         "monthly_contribution":mc,"annual_return_pct":ar,"horizon_months":hm4})',
'            mr2=ar/100/12',
'            fvs=[(ia*(1+mr2)**m)+(mc*(((1+mr2)**m-1)/mr2) if mr2>0 else mc*m) for m in range(1,hm4+1)]',
'            fig2=go.Figure(go.Scatter(x=list(range(1,hm4+1)),y=fvs,mode="lines",',
'                line=dict(color="#2563EB",width=2),fill="tozeroy",fillcolor="rgba(37,99,235,.07)"))',
'            fig2.update_layout(**_PL,height=180,title="Investment Growth")',
'            st.plotly_chart(fig2,use_container_width=True)',
'        else:',
'            section_header("\\U0001f3e6", "Parameters")',
'            la = st.number_input("Loan Amount ($)",1000.0,1e7,50000.0,1000.0)',
'            ai = st.slider("Interest Rate (%)",1.0,36.0,10.0,.5)',
'            tn = st.slider("Tenure (months)",6,360,60)',
'            if st.button("Run",key="fs5",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fin_r"]=_api("/api/simulation/financial","post",',
'                        {"sim_type":"loan_impact","loan_amount":la,',
'                         "annual_interest_pct":ai,"tenure_months":tn})',
'    with cp2:',
'        section_header("\\U0001f4ca", "Result")',
'        if "fin_r" in st.session_state: _render_result(st.session_state["fin_r"])',
'        else: empty_state("\\U0001f4b0","Run a simulation","Choose parameters and click Run.")',
'',
'# ── TAB 2: STUDY ──────────────────────────────────────────────────────────────',
'with tab_study:',
'    section_header("\\U0001f4da","Study Simulation","Model performance and exam preparation")',
'    ss = st.radio("Type",["Extra Hours","Exam Prep","Subject Improvement"],horizontal=True,key="ss")',
'    st.markdown("<div style=\'height:.5rem\'></div>",unsafe_allow_html=True)',
'    ss1,ss2=st.columns([1,1.5],gap="large")',
'    with ss1:',
'        if ss=="Extra Hours":',
'            eh=st.slider("Extra Hours/Day",0.5,8.0,1.0,.5)',
'            shw=st.slider("Horizon (weeks)",1,52,8,key="shw")',
'            if st.button("Run",key="ss_e",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["stu_r"]=_api("/api/simulation/study","post",',
'                        {"sim_type":"extra_hours","extra_hours_per_day":eh,"horizon_weeks":shw})',
'            base=summary.get("study_score",50) if summary and "error" not in summary else 50',
'            fig=go.Figure(go.Scatter(x=list(range(1,shw+1)),',
'                y=[min(100,base+eh*.4*w) for w in range(1,shw+1)],',
'                mode="lines+markers",line=dict(color="#7C3AED",width=2),',
'                fill="tozeroy",fillcolor="rgba(124,58,237,.07)"))',
'            fig.update_layout(**_PL,height=180,title="Performance Projection")',
'            st.plotly_chart(fig,use_container_width=True)',
'        elif ss=="Exam Prep":',
'            subj=st.text_input("Subject","Mathematics")',
'            de=st.slider("Days Until Exam",7,180,30)',
'            ts=st.slider("Target Score",50,100,80)',
'            if st.button("Run",key="ss_x",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["stu_r"]=_api("/api/simulation/study","post",',
'                        {"sim_type":"exam_prep","subject":subj,"days_until_exam":de,"target_score":ts})',
'        else:',
'            subj2=st.text_input("Subject","Python",key="subj2")',
'            tp=st.slider("Target Performance",50,100,80,key="tp")',
'            shw2=st.slider("Horizon (weeks)",1,52,8,key="shw2")',
'            if st.button("Run",key="ss_s",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["stu_r"]=_api("/api/simulation/study","post",',
'                        {"sim_type":"subject_improvement","subject":subj2,',
'                         "target_performance":tp,"horizon_weeks":shw2})',
'    with ss2:',
'        section_header("\\U0001f4ca","Result")',
'        if "stu_r" in st.session_state: _render_result(st.session_state["stu_r"])',
'        else: empty_state("\\U0001f4da","Run a simulation","Choose parameters and click Run.")',
'',
'# ── TAB 3: HABITS ─────────────────────────────────────────────────────────────',
'with tab_hab:',
'    section_header("\\U0001f525","Habit Simulation","Model new habits and focus improvements")',
'    hs = st.radio("Type",["New Habit","Remove Habit","Productivity"],horizontal=True,key="hs")',
'    st.markdown("<div style=\'height:.5rem\'></div>",unsafe_allow_html=True)',
'    hs1,hs2=st.columns([1,1.5],gap="large")',
'    with hs1:',
'        if hs=="New Habit":',
'            hn=st.text_input("Habit Name","Morning Meditation")',
'            hf=st.selectbox("Frequency",["daily","weekly","3x weekly"])',
'            hhw=st.slider("Horizon (weeks)",1,52,8,key="hhw")',
'            if st.button("Run",key="hs_n",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["hab_r"]=_api("/api/simulation/habits","post",',
'                        {"sim_type":"new_habit","habit_name":hn,"target_frequency":hf,"horizon_weeks":hhw})',
'            fig=go.Figure(go.Scatter(x=list(range(1,hhw+1)),',
'                y=[min(w*4.5,hhw*7) for w in range(1,hhw+1)],',
'                mode="lines+markers",line=dict(color="#F59E0B",width=2),',
'                fill="tozeroy",fillcolor="rgba(245,158,11,.07)"))',
'            fig.update_layout(**_PL,height=180,title="Projected Streak Growth")',
'            st.plotly_chart(fig,use_container_width=True)',
'        elif hs=="Remove Habit":',
'            hrn=st.text_input("Habit to Remove","Late Night Scrolling")',
'            hrhw=st.slider("Horizon (weeks)",1,52,4,key="hrhw")',
'            if st.button("Run",key="hs_r",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["hab_r"]=_api("/api/simulation/habits","post",',
'                        {"sim_type":"remove_habit","habit_name":hrn,"horizon_weeks":hrhw})',
'        else:',
'            fi2=st.slider("Focus Improvement (%)",-20,100,20,key="fi2")',
'            phw=st.slider("Horizon (weeks)",1,52,8,key="phw")',
'            if st.button("Run",key="hs_p",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["hab_r"]=_api("/api/simulation/habits","post",',
'                        {"sim_type":"productivity","focus_improvement_pct":fi2,"horizon_weeks":phw})',
'    with hs2:',
'        section_header("\\U0001f4ca","Result")',
'        if "hab_r" in st.session_state: _render_result(st.session_state["hab_r"])',
'        else: empty_state("\\U0001f525","Run a simulation","Choose parameters and click Run.")',
'',
'# ── TAB 4: FITNESS ────────────────────────────────────────────────────────────',
'with tab_fit:',
'    section_header("\\U0001f3c3","Fitness Simulation","Model workout plans and calorie burn")',
'    fs = st.radio("Type",["Workout Plan","Weight Loss","Goal Completion"],horizontal=True,key="fs_r")',
'    st.markdown("<div style=\'height:.5rem\'></div>",unsafe_allow_html=True)',
'    ft1,ft2=st.columns([1,1.5],gap="large")',
'    with ft1:',
'        if fs=="Workout Plan":',
'            spw=st.slider("Sessions/Week",1,7,3)',
'            dm=st.slider("Duration (min)",20,120,45)',
'            at=st.selectbox("Activity",["Running","Cycling","HIIT","Yoga","Weight Training","Mixed"])',
'            fhw=st.slider("Horizon (weeks)",1,52,8,key="fhw")',
'            if st.button("Run",key="ft_w",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fit_r"]=_api("/api/simulation/fitness","post",',
'                        {"sim_type":"workout_plan","sessions_per_week":spw,',
'                         "session_duration_minutes":float(dm),"activity_type":at,"horizon_weeks":fhw})',
'            cal_pw=spw*dm*7',
'            fig=go.Figure()',
'            fig.add_trace(go.Bar(x=list(range(1,fhw+1)),y=[cal_pw]*fhw,',
'                name="Weekly Burn",marker_color="#10B981",opacity=0.85))',
'            fig.add_trace(go.Scatter(x=list(range(1,fhw+1)),y=[cal_pw*w for w in range(1,fhw+1)],',
'                mode="lines",name="Cumulative",line=dict(color="#F59E0B",width=2),yaxis="y2"))',
'            fig.update_layout(**_PL,height=200,title="Calorie Projection",',
'                yaxis2=dict(overlaying="y",side="right",showgrid=False,tickfont=dict(color="#F59E0B")))',
'            st.plotly_chart(fig,use_container_width=True)',
'        elif fs=="Weight Loss":',
'            twc=st.slider("Target Weekly Calories",500,5000,1500,100)',
'            wlhw=st.slider("Horizon (weeks)",4,52,12,key="wlhw")',
'            if st.button("Run",key="ft_l",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fit_r"]=_api("/api/simulation/fitness","post",',
'                        {"sim_type":"weight_loss","target_weekly_calories":float(twc),"horizon_weeks":wlhw})',
'            fig2=go.Figure(go.Scatter(x=list(range(1,wlhw+1)),',
'                y=[twc*w/7700 for w in range(1,wlhw+1)],mode="lines+markers",',
'                line=dict(color="#EF4444",width=2),fill="tozeroy",fillcolor="rgba(239,68,68,.07)"))',
'            fig2.update_layout(**_PL,height=200,title="Projected Weight Loss (kg)")',
'            st.plotly_chart(fig2,use_container_width=True)',
'        else:',
'            gn=st.text_input("Goal Name","Run 5km")',
'            gchw=st.slider("Horizon (weeks)",1,52,8,key="gchw")',
'            if st.button("Run",key="ft_g",use_container_width=True):',
'                with st.spinner("Simulating..."):',
'                    st.session_state["fit_r"]=_api("/api/simulation/fitness","post",',
'                        {"sim_type":"goal_completion","goal_name":gn,"horizon_weeks":gchw})',
'    with ft2:',
'        section_header("\\U0001f4ca","Result")',
'        if "fit_r" in st.session_state: _render_result(st.session_state["fit_r"])',
'        else: empty_state("\\U0001f3c3","Run a simulation","Choose parameters and click Run.")',
'',
'# ── TAB 5: SCENARIO COMPARISON ────────────────────────────────────────────────',
'with tab_cmp:',
'    section_header("\\U0001f500","Scenario Comparison","Compare two paths head-to-head")',
'    SIM_MAP = {',
'        "Save $200/mo extra":       ("financial.savings_increase",  {"monthly_increase":200,"horizon_months":12}),',
'        "Cut expenses 15%":         ("financial.expense_reduction", {"reduction_pct":15,"horizon_months":12}),',
'        "Invest $5k @ 8% p.a.":     ("financial.investment_growth", {"initial_amount":5000,"monthly_contribution":200,"annual_return_pct":8,"horizon_months":24}),',
'        "Study 1h extra/day":       ("study.extra_hours",           {"extra_hours_per_day":1,"horizon_weeks":16}),',
'        "Study 2h extra/day":       ("study.extra_hours",           {"extra_hours_per_day":2,"horizon_weeks":16}),',
'        "Add morning habit":        ("habit.new_habit",             {"habit_name":"Morning Exercise","horizon_weeks":8}),',
'        "Boost focus 20%":          ("habit.productivity",          {"focus_improvement_pct":20,"horizon_weeks":8}),',
'        "Workout 3x/week":          ("fitness.workout_plan",        {"sessions_per_week":3,"session_duration_minutes":45,"activity_type":"Mixed","horizon_weeks":8}),',
'        "Workout 5x/week":          ("fitness.workout_plan",        {"sessions_per_week":5,"session_duration_minutes":45,"activity_type":"Mixed","horizon_weeks":8}),',
'    }',
'    cc1,cc2=st.columns(2,gap="large")',
'    with cc1:',
'        st.markdown(\'<div style="font-size:.8rem;font-weight:700;color:#60A5FA;\'',
'                    \'text-transform:uppercase;letter-spacing:.08em;margin-bottom:.5rem;">\'',
'                    \'Scenario A</div>\',unsafe_allow_html=True)',
'        sc_a=st.selectbox("Scenario A",list(SIM_MAP.keys()),index=0,key="sc_a")',
'    with cc2:',
'        st.markdown(\'<div style="font-size:.8rem;font-weight:700;color:#A78BFA;\'',
'                    \'text-transform:uppercase;letter-spacing:.08em;margin-bottom:.5rem;">\'',
'                    \'Scenario B</div>\',unsafe_allow_html=True)',
'        sc_b=st.selectbox("Scenario B",list(SIM_MAP.keys()),index=3,key="sc_b")',
'    cmp_h=st.slider("Comparison Horizon (months)",3,24,12,key="cmp_h")',
'    if st.button("Compare Scenarios",use_container_width=True,key="cmp_run"):',
'        at2,ap=SIM_MAP[sc_a]; bt2,bp=SIM_MAP[sc_b]',
'        with st.spinner("Comparing..."):',
'            st.session_state["cmp_r"]=_api("/api/scenarios/compare","post",{',
'                "scenario_a":{"name":sc_a,"sim_type":at2,"description":sc_a,"parameters":ap},',
'                "scenario_b":{"name":sc_b,"sim_type":bt2,"description":sc_b,"parameters":bp},',
'                "horizon_months":cmp_h,"domains":["financial","study","habits","fitness"],',
'            })',
'    if "cmp_r" in st.session_state:',
'        cr=st.session_state["cmp_r"]',
'        if "error" in cr: st.error(cr["error"])',
'        else:',
'            w2=cr.get("overall_winner","tie")',
'            wn=cr.get("scenario_a_name") if w2=="A" else (cr.get("scenario_b_name") if w2=="B" else "Tie")',
'            insight_card("success" if w2!="tie" else "info",',
'                         f"Winner: **{wn}** — {cr.get(\'recommendation\',\'\')}",',
'                         f"Confidence: {cr.get(\'confidence\',0)*100:.0f}%")',
'            impacts=cr.get("domain_impacts",[])',
'            if impacts:',
'                doms=[i["domain"].title() for i in impacts]',
'                sca=[i["scenario_a_score"] for i in impacts]',
'                scb=[i["scenario_b_score"] for i in impacts]',
'                fig=go.Figure()',
'                fig.add_trace(go.Bar(name=cr.get("scenario_a_name","A"),x=doms,y=sca,',
'                    marker_color="#2563EB",opacity=0.85))',
'                fig.add_trace(go.Bar(name=cr.get("scenario_b_name","B"),x=doms,y=scb,',
'                    marker_color="#7C3AED",opacity=0.85))',
'                fig.update_layout(**_PL,height=260,barmode="group",title="Domain Impact")',
'                st.plotly_chart(fig,use_container_width=True)',
'                fig_r=go.Figure()',
'                fig_r.add_trace(go.Scatterpolar(r=sca+[sca[0]],theta=doms+[doms[0]],',
'                    fill="toself",name=cr.get("scenario_a_name","A"),line=dict(color="#2563EB")))',
'                fig_r.add_trace(go.Scatterpolar(r=scb+[scb[0]],theta=doms+[doms[0]],',
'                    fill="toself",name=cr.get("scenario_b_name","B"),line=dict(color="#7C3AED")))',
'                fig_r.update_layout(paper_bgcolor="rgba(0,0,0,0)",',
'                    polar=dict(bgcolor="rgba(13,17,28,.8)",',
'                        radialaxis=dict(visible=True,color="#64748B"),',
'                        angularaxis=dict(color="#64748B")),',
'                    legend=dict(bgcolor="rgba(0,0,0,0)",font=dict(color="#94A3B8")),',
'                    height=300,title="Radar: Domain Coverage",',
'                    font=dict(family="Inter",color="#94A3B8"),)',
'                st.plotly_chart(fig_r,use_container_width=True)',
'    else:',
'        with st.spinner("Loading best path..."):',
'            best=_api("/api/scenarios/best-path")',
'        if best and "error" not in best:',
'            section_header("\\U0001f3c6","Recommended Best Path")',
'            insight_card("prediction",',
'                f"**{best.get(\'recommended_path\',\'\')}** — {best.get(\'path_description\',\'\')}",',
'                f"Expected gain: +{best.get(\'expected_score_gain\',0):.1f} pts")',
'            for act in best.get("top_actions",[])[:3]:',
'                insight_card("tip",act)',
'',
'# ── TAB 6: RECOMMENDATIONS ────────────────────────────────────────────────────',
'with tab_rec:',
'    section_header("\\U0001f4a1","AI Recommendations","Prioritised action plan from your data")',
'    if st.button("Refresh",key="rec_ref",use_container_width=True):',
'        with st.spinner("Generating..."):',
'            st.session_state["rec_d"]=_api("/api/digital-twin/recommendations","post",{})',
'    elif "rec_d" not in st.session_state:',
'        with st.spinner("Loading..."):',
'            st.session_state["rec_d"]=_api("/api/digital-twin/recommendations","post",{})',
'    rd=st.session_state.get("rec_d",{})',
'    if rd and "error" not in rd:',
'        hs2=rd.get("overall_health_score",0)',
'        st.markdown(',
'            \'<div style="background:rgba(37,99,235,.08);border:1px solid rgba(37,99,235,.2);\' +',
'            \'border-radius:12px;padding:.75rem 1.5rem;margin-bottom:1rem;\' +',
'            \'display:flex;align-items:center;justify-content:space-between;">\' +',
'            \'<span style="color:#94A3B8;">Overall Health Score</span>\' +',
'            f\'<span style="font-size:1.5rem;font-weight:800;color:#60A5FA;">{hs2:.0f}/100</span></div>\',',
'            unsafe_allow_html=True)',
'        recs=rd.get("recommendations",[])',
'        if recs:',
'            doms2=list({r["domain"] for r in recs})',
'            sel=st.multiselect("Filter domain",doms2,default=doms2,key="rec_dom")',
'            for rec in [r for r in recs if r["domain"] in sel]:',
'                pc={"high":"#EF4444","medium":"#F59E0B","low":"#10B981"}.get(rec.get("priority","low"),"#64748B")',
'                ic={"high":"#EF4444","medium":"#F59E0B","low":"#10B981"}.get(rec.get("impact","low"),"#64748B")',
'                st.markdown(',
'                    \'<div style="background:rgba(13,17,28,.9);border:1px solid rgba(37,99,235,.12);\' +',
'                    \'border-radius:14px;padding:1.25rem 1.5rem;margin-bottom:.75rem;">\' +',
'                    \'<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:.5rem;">\' +',
'                    f\'<div style="font-size:1rem;font-weight:700;color:#F1F5F9;">{rec.get("title","")}</div>\' +',
'                    \'<div style="display:flex;gap:.5rem;">\' +',
'                    f\'<span style="border-radius:99px;padding:2px 8px;font-size:.68rem;font-weight:700;\' +',
'                    f\'background:rgba(37,99,235,.1);color:#64748B;">{rec.get("domain","").upper()}</span>\' +',
'                    f\'<span style="border-radius:99px;padding:2px 8px;font-size:.68rem;font-weight:700;color:{pc};">\' +',
'                    f\'P:{rec.get("priority","").upper()}</span>\' +',
'                    f\'<span style="border-radius:99px;padding:2px 8px;font-size:.68rem;font-weight:700;color:{ic};">\' +',
'                    f\'I:{rec.get("impact","").upper()}</span></div></div>\' +',
'                    f\'<div style="font-size:.85rem;color:#CBD5E1;margin-bottom:.5rem;">{rec.get("description","")}</div>\',',
'                    unsafe_allow_html=True)',
'                for i2,step in enumerate(rec.get("action_steps",[]),1):',
'                    st.markdown(',
'                        f\'<div style="display:flex;gap:.5rem;margin-bottom:.2rem;">\' +',
'                        f\'<span style="color:#2563EB;font-weight:700;font-size:.8rem;flex-shrink:0;">{i2}.</span>\' +',
'                        f\'<span style="font-size:.8rem;color:#94A3B8;">{step}</span></div>\',',
'                        unsafe_allow_html=True)',
'                progress_bar("Confidence",rec.get("confidence",0.5)*100,100,',
'                    f"linear-gradient(90deg,{pc},{pc}88)")',
'        else: empty_state("\\U0001f4a1","No recommendations","Add data to unlock insights.")',
'    else: empty_state("\\U0001f4a1","Loading...","Generating recommendations.")',
'',
'# ── TAB 7: RISK ───────────────────────────────────────────────────────────────',
'with tab_risk:',
'    section_header("\\u26a0\\ufe0f","Risk Analysis","Current risk exposure across all domains")',
'    if st.button("Refresh Risk",key="risk_ref",use_container_width=True):',
'        with st.spinner("Analysing..."):',
'            st.session_state["risk_d"]=_api("/api/digital-twin/risk")',
'    elif "risk_d" not in st.session_state:',
'        with st.spinner("Loading..."):',
'            st.session_state["risk_d"]=_api("/api/digital-twin/risk")',
'    rd2=st.session_state.get("risk_d",{})',
'    if rd2 and "error" not in rd2:',
'        ors=rd2.get("overall_risk_score",0)',
'        rl2=rd2.get("risk_level","medium")',
'        safe2=rd2.get("safe_to_proceed",True)',
'        rlc={"low":"#10B981","medium":"#F59E0B","high":"#EF4444"}.get(rl2,"#F59E0B")',
'        rc1,rc2,rc3=st.columns(3)',
'        with rc1:',
'            st.markdown(',
'                \'<div style="background:rgba(13,17,28,.9);border:1px solid rgba(37,99,235,.15);\' +',
'                \'border-radius:12px;padding:1.25rem;text-align:center;">\' +',
'                \'<div style="font-size:.7rem;color:#64748B;text-transform:uppercase;">Overall Risk</div>\' +',
'                f\'<div style="font-size:2.5rem;font-weight:800;color:{rlc};">{ors:.0f}</div>\' +',
'                f\'<div style="font-size:.8rem;color:{rlc};font-weight:600;">{rl2.upper()}</div></div>\',',
'                unsafe_allow_html=True)',
'        with rc2:',
'            st.markdown(',
'                \'<div style="background:rgba(13,17,28,.9);border:1px solid rgba(37,99,235,.15);\' +',
'                \'border-radius:12px;padding:1.25rem;text-align:center;">\' +',
'                \'<div style="font-size:.7rem;color:#64748B;text-transform:uppercase;">Safe to Proceed</div>\' +',
'                f\'<div style="font-size:2.5rem;font-weight:800;color:{"#10B981" if safe2 else "#EF4444"};">\' +',
'                f\'{"\\u2713" if safe2 else "\\u2717"}</div>\' +',
'                f\'<div style="font-size:.8rem;color:{"#10B981" if safe2 else "#EF4444"};font-weight:600;">\' +',
'                f\'{"PROCEED" if safe2 else "REVIEW"}</div></div>\',',
'                unsafe_allow_html=True)',
'        with rc3:',
'            facts=rd2.get("risk_factors",[])',
'            hc=sum(1 for f in facts if f.get("severity") in ("high","critical"))',
'            st.markdown(',
'                \'<div style="background:rgba(13,17,28,.9);border:1px solid rgba(37,99,235,.15);\' +',
'                \'border-radius:12px;padding:1.25rem;text-align:center;">\' +',
'                \'<div style="font-size:.7rem;color:#64748B;text-transform:uppercase;">High Risk Factors</div>\' +',
'                f\'<div style="font-size:2.5rem;font-weight:800;color:{"#EF4444" if hc>0 else "#10B981"};">{hc}</div>\' +',
'                f\'<div style="font-size:.8rem;color:#64748B;">of {len(facts)} total</div></div>\',',
'                unsafe_allow_html=True)',
'        if facts:',
'            st.markdown("<div style=\'height:1rem\'></div>",unsafe_allow_html=True)',
'            section_header("\\U0001f5fa\\ufe0f","Risk Heatmap")',
'            dom_risk={}',
'            for f in facts:',
'                sv={"low":25,"medium":50,"high":75,"critical":100}.get(f.get("severity","low"),25)',
'                dom_risk[f.get("domain","?")]=max(dom_risk.get(f.get("domain","?"),0),sv)',
'            all_doms=["financial","study","habits","fitness","goals"]',
'            rv=[dom_risk.get(d,5) for d in all_doms]',
'            rcols=["#10B981" if v<30 else "#F59E0B" if v<60 else "#EF4444" for v in rv]',
'            fig_h=go.Figure(go.Bar(x=all_doms,y=rv,marker_color=rcols,opacity=0.85,',
'                text=[str(v) for v in rv],textposition="outside",textfont=dict(color="#94A3B8",size=11)))',
'            fig_h.update_layout(**_PL,height=260,',
'                yaxis=dict(**_PL["yaxis"],range=[0,110]),',
'                title="Risk Score by Domain (0=safe, 100=critical)")',
'            st.plotly_chart(fig_h,use_container_width=True)',
'            section_header("\\U0001f50d","Risk Factors")',
'            for f in facts:',
'                sv2=f.get("severity","low")',
'                ct="warning" if sv2 in ("medium","high","critical") else "success"',
'                insight_card(ct,',
'                    f"**[{f.get(\'domain\',\'\').upper()} / {sv2.upper()}]** {f.get(\'description\',\'\')} — *{f.get(\'mitigation\',\'\')}*",',
'                    f"Probability: {f.get(\'probability\',0)*100:.0f}%")',
'    else: empty_state("\\u26a0\\ufe0f","Loading risk analysis...","Analysing your data.")',
)

src = "\n".join(lines)

import ast
try:
    ast.parse(src)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(src)
    print(f"WRITTEN OK  |  {src.count(chr(10))} lines  |  path: {out}")
except SyntaxError as e:
    print(f"SYNTAX ERROR: {e}")
